# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bcbf457131035852db2fd22e5b67fb11f72b0fba567c035691a3928f4b5fed46fb8f7dbcb1503e0807b3960f650f8dc65ffefc42a38361c7dca1406ffad3611

test:
  secret_key_base: 2995873322673edb7a811abdccc806e50ed96a0fa14fa1bb67c4b09995a85111aa18daf5200e863036422716374f715a33745b7e344d58e26d8b2dc052001fb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
